version: 2

sources:
  - name: raw_data #arbitrary name for the source
    description: "raw data sources for NYC taxi rides"
    database: kestra-sandbox-504814 #BigQuery project ID
    schema: zoomcamp #Dataset name
    tables:
      - name: green_tripdata
      - name: yellow_tripdata
      - name: fhv_tripdata

